# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZjE1YWQ4MWNlYmI0N2FiZTVkMTZiY2VkMGI4MTFlOGJiNGZmYTU3OTI4NjkxOGU3ODQ3NjAwMGM5Yzg2ODdlNGE0Y2U1MDI3NjZmZGFhZjI2ZWRjYTM4MDAzZmFkOWM3NDg0ZjQ1Yjc3ZTc5MzA4NTExMmYxM2RlOWUxZTExZTQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
